language: node_js

node_js:
  - node

jobs:
  include:
    - stage: tests
      script:
        - npm run build
        - npm test

    # Deploy translation keys to Crowdin if we are on develop or one of the release branches
    - stage: deployment
      install: skip
      script: skip
      deploy:
        provider: script
        script: bash .travis-deploy.sh
        on:
          branch: production
