name: Build & test

on: [pull_request, push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: npm run build
    - run: npm test


    # Prepare test deployment
    - name: Build for test deployment
      env:
        REACT_APP_INCLUDE_LEGAL_NOTICES: 1
      run: |
        builddate="$(date --utc '+%Y-%m-%d_%H-%M-%S')"
        buildno="$(printf '%06d' "${{ github.run_id }}")"
        if [[ $GITHUB_REF == refs/pull/* ]]; then
          tmp="${GITHUB_REF#refs/pull/}"
          prnum="${tmp%/merge}"
          deploydir="${builddate}-pr${prnum}-${buildno}"
        else
          branch="${GITHUB_REF#refs/heads/}"
          deploydir="${builddate}-${{ github.repository_owner }}-${buildno}-${branch}"
        fi
        deploydir="/$(echo "${deploydir}" | LC_ALL=C sed -e 's/[^a-zA-Z0-9\-_]/-/g')"
        echo ${deploydir} > deploydir.tmp
        PUBLIC_URL=${deploydir} npm run build

    - name: Archive test deployment files as artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-deployment-files
        path: |
          build
          .github/.deploy-settings.toml
          deploydir.tmp

    # Prepare production deployment
    - name: Build for prod deployment
      if: github.repository_owner == 'elan-ev' && github.ref == 'refs/heads/master'
      env:
        REACT_APP_INCLUDE_LEGAL_NOTICES: 1
      run: |
        rm -rf build
        PUBLIC_URL="/" npm run build

    - name: Archive prod deployment files as artifact
      if: github.repository_owner == 'elan-ev' && github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v2
      with:
        name: prod-deployment-files
        path: |
          build
          .github/.deploy-settings.toml
